`pip install numpy`

In [3]:
import numpy as np #data science

In [4]:
n1 = np.array([1,2,3,4])
print(n1)
print(type(n1))

[1 2 3 4]
<class 'numpy.ndarray'>


In [5]:
n1

array([1, 2, 3, 4])

In [6]:
x = []
len(dir(x)) #list functions

47

In [7]:
len(dir(n1))

165

In [8]:
n1.shape

(4,)

In [10]:
n2 = np.array([[1,2,3],[2,3,5]])
print(n2)
print(n2.shape)

[[1 2 3]
 [2 3 5]]
(2, 3)


Creating matrix
- arange
- linspace
- random.rand
- random.randn
- random.randomInt
- eyes
- ones
- zeros

#range cannot split with 0.2 values
#arange can 
- range(1,10,0.4) nhi chalega
- arange(1,10,.2) chalega


In [12]:
x = np.arange(-10,10,.2)
x.shape

(100,)

In [16]:
y = np.linspace(1,5,10) #inclusive h (i.e will include 1 and 5) and last mei no of elements jo generate karsne hai!
print(y)

[1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]


In [19]:
np.random.rand()

0.8169803759949728

In [20]:
np.random.rand(10)

array([0.03273984, 0.24270276, 0.33911018, 0.8250492 , 0.60782125,
       0.21233568, 0.35252013, 0.16153129, 0.33492961, 0.25855737])

In [21]:
np.random.randn(10) #random normal - generates random sequence surrounding 0

array([ 0.50950751,  0.88592878,  0.90343311, -1.02534741, -0.96647696,
       -0.38039571,  0.47798987,  0.44772532, -0.57544981, -1.14487905])

In [24]:
np.random.randint(1,5,(5,5))

array([[2, 4, 1, 3, 1],
       [1, 4, 3, 3, 1],
       [1, 3, 4, 3, 3],
       [2, 4, 1, 3, 2],
       [1, 4, 3, 4, 2]])

In [27]:
x = np.random.randint(1,10,(3,2))
y = np.random.randint(1,10,(3,2))
print(x)
print(y)

[[2 4]
 [9 5]
 [4 8]]
[[3 8]
 [5 7]
 [8 8]]


In [28]:
x + 5

array([[ 7,  9],
       [14, 10],
       [ 9, 13]])

In [29]:
x + y

array([[ 5, 12],
       [14, 12],
       [12, 16]])

In [30]:
x/y

array([[0.66666667, 0.5       ],
       [1.8       , 0.71428571],
       [0.5       , 1.        ]])

In [31]:
x *y

array([[ 6, 32],
       [45, 35],
       [32, 64]])

In [32]:
x.T #transpose

array([[2, 9, 4],
       [4, 5, 8]])

In [33]:
x.dot(y.T)

array([[ 38,  38,  48],
       [ 67,  80, 112],
       [ 76,  76,  96]])

In [36]:
np.sin(x)

array([[ 0.90929743, -0.7568025 ],
       [ 0.41211849, -0.95892427],
       [-0.7568025 ,  0.98935825]])

In [37]:
print(x.sum())
print(x.min())
print(x.max())
print(x.mean())
print(x.std())

32
2
9
5.333333333333333
2.4267032964268394
